# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{hash_syntax}
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{Michael Edgar}]
  s.date = %q{2011-06-24}
  s.description = %q{The new label style for Ruby 1.9's literal hash keys
is somewhat controversial. This tool seamlessly converts Ruby files between
the old and the new syntaxes.}
  s.email = %q{michael.j.edgar@dartmouth.edu}
  s.executables = [%q{hash_syntax}]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "bin/hash_syntax",
    "hash_syntax.gemspec",
    "lib/hash_syntax.rb",
    "lib/hash_syntax/runner.rb",
    "lib/hash_syntax/token.rb",
    "lib/hash_syntax/transformer.rb",
    "lib/hash_syntax/version.rb",
    "spec/hash_syntax_spec.rb",
    "spec/spec.opts",
    "spec/spec_helper.rb",
    "spec/transformer_spec.rb"
  ]
  s.homepage = %q{http://github.com/michaeledgar/hash_syntax}
  s.require_paths = [%q{lib}]
  s.rubygems_version = %q{1.8.5}
  s.summary = %q{Converts Ruby files to and from Ruby 1.9's Hash syntax}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<object_regex>, ["~> 1.0.1"])
      s.add_runtime_dependency(%q<trollop>, ["~> 1.16.2"])
      s.add_development_dependency(%q<rspec>, [">= 2.3.0"])
      s.add_development_dependency(%q<yard>, [">= 0"])
    else
      s.add_dependency(%q<object_regex>, ["~> 1.0.1"])
      s.add_dependency(%q<trollop>, ["~> 1.16.2"])
      s.add_dependency(%q<rspec>, [">= 2.3.0"])
      s.add_dependency(%q<yard>, [">= 0"])
    end
  else
    s.add_dependency(%q<object_regex>, ["~> 1.0.1"])
    s.add_dependency(%q<trollop>, ["~> 1.16.2"])
    s.add_dependency(%q<rspec>, [">= 2.3.0"])
    s.add_dependency(%q<yard>, [">= 0"])
  end
end

